// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpvknjBjxON7df7DxZoVfdn_XOPwnQSyE',
    appId: '1:448880362653:web:53be0fe2fc97d8d9e48074',
    messagingSenderId: '448880362653',
    projectId: 'smartdzmeal',
    authDomain: 'smartdzmeal.firebaseapp.com',
    storageBucket: 'smartdzmeal.firebasestorage.app',
    measurementId: 'G-YZJJNP0VKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRHl8F1pNyKPZs2UJHQmwIdbXo_-B1HIc',
    appId: '1:448880362653:android:3c6e08527493928ae48074',
    messagingSenderId: '448880362653',
    projectId: 'smartdzmeal',
    storageBucket: 'smartdzmeal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvXn_CFYASu1em5DQ-d8t3aZuyQweuHSs',
    appId: '1:448880362653:ios:54f70b9bf3c38ddee48074',
    messagingSenderId: '448880362653',
    projectId: 'smartdzmeal',
    storageBucket: 'smartdzmeal.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvXn_CFYASu1em5DQ-d8t3aZuyQweuHSs',
    appId: '1:448880362653:ios:54f70b9bf3c38ddee48074',
    messagingSenderId: '448880362653',
    projectId: 'smartdzmeal',
    storageBucket: 'smartdzmeal.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpvknjBjxON7df7DxZoVfdn_XOPwnQSyE',
    appId: '1:448880362653:web:aa912722f97974ade48074',
    messagingSenderId: '448880362653',
    projectId: 'smartdzmeal',
    authDomain: 'smartdzmeal.firebaseapp.com',
    storageBucket: 'smartdzmeal.firebasestorage.app',
    measurementId: 'G-PMH2J514VF',
  );
}
